
export default eventHandler(async (event) => {

  return [
    {
      'id': 505,
      'name': 'NuxtJS (EN)',
      'created_at': '2021-01-19T16:45:07.626Z',
      'updated_at': '2022-10-26T12:17:57.589Z',
      'groups': [
        {
          'id': 305,
          'name': 'Featured',
          'created_at': '2021-01-19T16:45:12.655Z',
          'updated_at': '2022-10-26T12:17:57.585Z',
          'position': 750,
          'showcases': [
            {
              'id': 4752,
              'domain': 'ecosia.org',
              'hostname': 'ecosia.org',
              'url': 'https://ecosia.org/',
              'hasSSR': true,
              'isStatic': false,
              'vueVersion': '2.6.11',
              'screenshotUrl': 'vue-telemetry/a5d4be7e33f3dac04b225c201587bae9.jpg',
              'slug': 'ecosia-org',
              'uiVersion': null,
              'frameworkVersion': null,
              'lastDetectedAt': '2021-02-04T19:01:33.536Z',
              'ui': null,
              'framework': {
                'id': 1,
                'slug': 'nuxtjs',
                'name': 'Nuxt',
                'url': 'https://nuxt.com',
                'imgPath': '/framework/nuxt.svg',
                'createdAt': '2020-06-23T12:39:28.355Z',
                'updatedAt': '2023-09-02T08:27:39.984Z'
              },
              'title': 'Ecosia - the search engine that plants trees',
              'description': 'Ecosia uses the ad revenue from your searches to plant trees where they are needed the most. By searching with Ecosia, you’re not only reforesting our planet, but you’re also empowering the communities around our planting projects to build a better future for themselves. Give it a try!',
              'language': 'en',
              'favicon': null,
              'createdAt': '2020-07-09T13:14:15.290Z',
              'updatedAt': '2021-02-04T19:01:33.806Z',
              'isFeatured': true,
              'siteName': '',
              'rank': '492',
              'list_group_id': 305,
              'showcase_id': 4752,
              'position': 1500
            },
            {
              'id': 15214,
              'domain': 'upwork.com',
              'hostname': 'upwork.com',
              'url': 'https://upwork.com/',
              'hasSSR': true,
              'isStatic': false,
              'vueVersion': '2.7.10',
              'screenshotUrl': 'vue-telemetry/5913ce3a99defcd8778162850ee80657.jpg',
              'slug': 'upwork-com',
              'uiVersion': null,
              'frameworkVersion': null,
              'lastDetectedAt': '2022-11-25T00:05:17.202Z',
              'ui': null,
              'framework': {
                'id': 1,
                'slug': 'nuxtjs',
                'name': 'Nuxt',
                'url': 'https://nuxt.com',
                'imgPath': '/framework/nuxt.svg',
                'createdAt': '2020-06-23T12:39:28.355Z',
                'updatedAt': '2023-09-02T08:27:39.984Z'
              },
              'title': 'Upwork | The World’s Work Marketplace',
              'description': 'Upwork connects businesses with independent professionals and agencies around the globe. Where companies and freelancers work together in new ways that unlock their potential.',
              'language': 'en',
              'favicon': null,
              'createdAt': '2020-09-15T15:07:25.475Z',
              'updatedAt': '2022-11-25T00:05:17.379Z',
              'isFeatured': false,
              'siteName': 'Upwork',
              'rank': '187',
              'list_group_id': 305,
              'showcase_id': 15214,
              'position': 2000
            },
            {
              'id': 33542,
              'domain': 'rakuten.co.jp',
              'hostname': 'nba.rakuten.co.jp',
              'url': 'https://nba.rakuten.co.jp:/',
              'hasSSR': true,
              'isStatic': false,
              'vueVersion': '2.7.14',
              'screenshotUrl': 'vue-telemetry/b27c5893a311796eccd82cd5884f78c5.jpg',
              'slug': 'nba-rakuten-co-jp',
              'uiVersion': null,
              'frameworkVersion': null,
              'lastDetectedAt': '2023-04-17T06:30:57.613Z',
              'ui': null,
              'framework': {
                'id': 1,
                'slug': 'nuxtjs',
                'name': 'Nuxt',
                'url': 'https://nuxt.com',
                'imgPath': '/framework/nuxt.svg',
                'createdAt': '2020-06-23T12:39:28.355Z',
                'updatedAt': '2023-09-02T08:27:39.984Z'
              },
              'title': 'NBA Rakuten公式 - NBAの試合をLIVEや動画で楽しもう！',
              'description': 'NBAを観るなら【NBA Rakuten】！NBAの試合をLIVEや見逃し動画配信！最新ニュース・無料動画・選手やチーム情報も！ベーシック／リーグパス等プラン豊富。アプリで動画ダウンロード可・らくらく視聴！ライブチャットやコミュニティ機能付き！',
              'language': '',
              'favicon': null,
              'createdAt': '2020-11-19T06:36:45.643Z',
              'updatedAt': '2023-04-17T06:30:58.406Z',
              'isFeatured': false,
              'siteName': '',
              'rank': '88',
              'list_group_id': 305,
              'showcase_id': 33542,
              'position': 6000
            },
            {
              'id': 40244,
              'domain': 'tiktok.com',
              'hostname': 'tiktok.com',
              'url': 'https://tiktok.com/business/es',
              'hasSSR': true,
              'isStatic': false,
              'vueVersion': '2.6.12',
              'screenshotUrl': 'vue-telemetry/90ddab9e41f138afa8ac5cf6e18ccb18.jpg',
              'slug': 'tiktok-com',
              'uiVersion': null,
              'frameworkVersion': null,
              'lastDetectedAt': '2021-10-26T00:01:32.759Z',
              'ui': null,
              'framework': {
                'id': 1,
                'slug': 'nuxtjs',
                'name': 'Nuxt',
                'url': 'https://nuxt.com',
                'imgPath': '/framework/nuxt.svg',
                'createdAt': '2020-06-23T12:39:28.355Z',
                'updatedAt': '2023-09-02T08:27:39.984Z'
              },
              'title': 'TikTok For Business: marketing en TikTok',
              'description': 'Llega a diversas audiencias en todo el mundo con TikTok For Business, una plataforma integral de soluciones de marketing.',
              'language': 'es',
              'favicon': null,
              'createdAt': '2020-12-17T15:27:30.716Z',
              'updatedAt': '2021-10-26T00:01:32.905Z',
              'isFeatured': false,
              'siteName': '',
              'rank': '87',
              'list_group_id': 305,
              'showcase_id': 40244,
              'position': 7000
            },
            {
              'id': 46345,
              'domain': 'nasa.gov',
              'hostname': 'jpl.nasa.gov',
              'url': 'https://jpl.nasa.gov:/',
              'hasSSR': true,
              'isStatic': false,
              'vueVersion': '2.6.14',
              'screenshotUrl': 'vue-telemetry/9752872b22fbfbdf7b9e8bac19264f43.jpg',
              'slug': 'jpl-nasa-gov',
              'uiVersion': null,
              'frameworkVersion': null,
              'lastDetectedAt': '2023-04-11T20:00:32.187Z',
              'ui': {
                'id': 1,
                'slug': 'tailwind-css',
                'name': 'Tailwind CSS',
                'url': 'https://tailwindcss.com/',
                'imgPath': '/ui/tailwind.svg',
                'createdAt': '2020-06-24T09:13:44.270Z',
                'updatedAt': '2023-09-03T11:30:19.605Z'
              },
              'framework': {
                'id': 1,
                'slug': 'nuxtjs',
                'name': 'Nuxt',
                'url': 'https://nuxt.com',
                'imgPath': '/framework/nuxt.svg',
                'createdAt': '2020-06-23T12:39:28.355Z',
                'updatedAt': '2023-09-02T08:27:39.984Z'
              },
              'title': 'NASA Jet Propulsion Laboratory (JPL) - Robotic Space Exploration',
              'description': 'Space mission and science news, images and videos from NASA s Jet Propulsion Laboratory, the leading center for robotic exploration of the solar system.',
              'language': 'en',
              'favicon': null,
              'createdAt': '2021-01-14T06:17:22.577Z',
              'updatedAt': '2023-04-11T20:00:32.464Z',
              'isFeatured': false,
              'siteName': 'NASA Jet Propulsion Laboratory (JPL)',
              'rank': '9007199254740991',
              'list_group_id': 305,
              'showcase_id': 46345,
              'position': 9000
            },
            {
              'id': 66297,
              'domain': 'unilever.com',
              'hostname': 'unilever.com',
              'url': 'https://unilever.com:/',
              'hasSSR': false,
              'isStatic': true,
              'vueVersion': '3.3.4',
              'screenshotUrl': 'vue-telemetry/f88bac390770d6bcf39f6c041cf00897.jpg',
              'slug': 'unilever-com',
              'uiVersion': null,
              'frameworkVersion': null,
              'lastDetectedAt': '2023-08-09T13:42:16.973Z',
              'ui': {
                'id': 1,
                'slug': 'tailwind-css',
                'name': 'Tailwind CSS',
                'url': 'https://tailwindcss.com/',
                'imgPath': '/ui/tailwind.svg',
                'createdAt': '2020-06-24T09:13:44.270Z',
                'updatedAt': '2023-09-03T11:30:19.605Z'
              },
              'framework': null,
              'title': 'Unilever Global: Making sustainable living commonplace | Unilever',
              'description': 'At Unilever we meet everyday needs for nutrition, hygiene and personal care with brands that help people feel good, look good and get more out of life.',
              'language': 'en',
              'favicon': null,
              'createdAt': '2021-03-22T08:58:50.312Z',
              'updatedAt': '2023-08-09T13:42:17.265Z',
              'isFeatured': false,
              'siteName': 'Unilever',
              'rank': '9007199254740991',
              'list_group_id': 305,
              'showcase_id': 66297,
              'position': 12000
            },
            {
              'id': 88450,
              'domain': 'volta.net',
              'hostname': 'volta.net',
              'url': 'https://volta.net:/',
              'hasSSR': true,
              'isStatic': true,
              'vueVersion': '3.2.47',
              'screenshotUrl': 'vue-telemetry/32abc3212c97fd44ff24acaa6edc4573.jpg',
              'slug': 'volta-net',
              'uiVersion': null,
              'frameworkVersion': null,
              'lastDetectedAt': '2023-04-02T04:31:29.489Z',
              'ui': {
                'id': 1,
                'slug': 'tailwind-css',
                'name': 'Tailwind CSS',
                'url': 'https://tailwindcss.com/',
                'imgPath': '/ui/tailwind.svg',
                'createdAt': '2020-06-24T09:13:44.270Z',
                'updatedAt': '2023-09-03T11:30:19.605Z'
              },
              'framework': {
                'id': 1,
                'slug': 'nuxtjs',
                'name': 'Nuxt',
                'url': 'https://nuxt.com',
                'imgPath': '/framework/nuxt.svg',
                'createdAt': '2020-06-23T12:39:28.355Z',
                'updatedAt': '2023-09-02T08:27:39.984Z'
              },
              'title': 'Supercharged GitHub Experience · Volta',
              'description': 'Work with your team on open-source and private repositories, all in one place.',
              'language': 'en',
              'favicon': null,
              'createdAt': '2021-06-22T10:41:39.400Z',
              'updatedAt': '2023-04-02T04:31:29.868Z',
              'isFeatured': true,
              'siteName': 'Volta',
              'rank': '9007199254740991',
              'list_group_id': 305,
              'showcase_id': 88450,
              'position': 3500
            },
            {
              'id': 106563,
              'domain': 'mvm350.ir',
              'hostname': 'mvm350.ir',
              'url': 'https://mvm350.ir:/',
              'hasSSR': true,
              'isStatic': false,
              'vueVersion': '2.7.10',
              'screenshotUrl': 'vue-telemetry/1d7ae27ea6062aad56d471e7a7ee55ab.jpg',
              'slug': 'mvm350-ir',
              'uiVersion': null,
              'frameworkVersion': null,
              'lastDetectedAt': '2023-03-27T11:36:10.904Z',
              'ui': {
                'id': 6,
                'slug': 'vuetify',
                'name': 'Vuetify',
                'url': 'https://vuetifyjs.com/',
                'imgPath': '/ui/vuetify.svg',
                'createdAt': '2020-07-03T08:46:55.477Z',
                'updatedAt': '2023-09-03T10:23:18.897Z'
              },
              'framework': {
                'id': 1,
                'slug': 'nuxtjs',
                'name': 'Nuxt',
                'url': 'https://nuxt.com',
                'imgPath': '/framework/nuxt.svg',
                'createdAt': '2020-06-23T12:39:28.355Z',
                'updatedAt': '2023-09-02T08:27:39.984Z'
              },
              'title': 'دهقان پور - نمایندگی مدیران خودرو 350',
              'description': 'نمایندگی مدیران خودرو ۳۵۰ به عنوان نماینده رسمی مدیران خودرو و چری MVM CHERY ، ارائه دهنده محصولات مدیران خودرو با شرایط فروش اقساطی بلند مدت - مدیریت دهقان پور ۰۲۱۷۷۶۸۱۶۹۴',
              'language': 'fa',
              'favicon': null,
              'createdAt': '2021-09-18T13:56:42.689Z',
              'updatedAt': '2023-03-27T11:36:15.437Z',
              'isFeatured': false,
              'siteName': 'نمایندگی مدیران خودرو 350',
              'rank': '9007199254740991',
              'list_group_id': 305,
              'showcase_id': 106563,
              'position': 15000
            },
            {
              'id': 107436,
              'domain': 'monopo.london',
              'hostname': 'monopo.london',
              'url': 'https://monopo.london:/',
              'hasSSR': true,
              'isStatic': true,
              'vueVersion': '2.6.14',
              'screenshotUrl': 'vue-telemetry/017f61965a8b4dd0d5f423b1c57abad0.jpg',
              'slug': 'monopo-london',
              'uiVersion': null,
              'frameworkVersion': null,
              'lastDetectedAt': '2023-04-07T08:35:49.741Z',
              'ui': null,
              'framework': {
                'id': 1,
                'slug': 'nuxtjs',
                'name': 'Nuxt',
                'url': 'https://nuxt.com',
                'imgPath': '/framework/nuxt.svg',
                'createdAt': '2020-06-23T12:39:28.355Z',
                'updatedAt': '2023-09-02T08:27:39.984Z'
              },
              'title': 'monopo london | Tokyo-born design-driven creative agency.',
              'description': 'We are a design-driven creative agency working accross branding, digital design and communications. Based in London, born in Tokyo.',
              'language': 'en',
              'favicon': null,
              'createdAt': '2021-09-22T10:11:47.792Z',
              'updatedAt': '2023-04-07T08:35:50.093Z',
              'isFeatured': false,
              'siteName': '',
              'rank': '9007199254740991',
              'list_group_id': 305,
              'showcase_id': 107436,
              'position': 11000
            },
            {
              'id': 108464,
              'domain': 'findadiscord.com',
              'hostname': 'findadiscord.com',
              'url': 'https://findadiscord.com:/',
              'hasSSR': true,
              'isStatic': false,
              'vueVersion': '2.6.14',
              'screenshotUrl': 'vue-telemetry/16625a1b2c2ea668d68ddae2022f54d1.jpg',
              'slug': 'findadiscord-com',
              'uiVersion': null,
              'frameworkVersion': null,
              'lastDetectedAt': '2023-04-02T08:02:27.500Z',
              'ui': {
                'id': 3,
                'slug': 'bootstrap-vue',
                'name': 'Bootstrap Vue',
                'url': 'https://bootstrap-vue.org/',
                'imgPath': '/ui/bootstrap.svg',
                'createdAt': '2020-07-03T08:46:54.161Z',
                'updatedAt': '2023-09-03T11:50:00.959Z'
              },
              'framework': {
                'id': 1,
                'slug': 'nuxtjs',
                'name': 'Nuxt',
                'url': 'https://nuxt.com',
                'imgPath': '/framework/nuxt.svg',
                'createdAt': '2020-06-23T12:39:28.355Z',
                'updatedAt': '2023-09-02T08:27:39.984Z'
              },
              'title': 'Find A Discord',
              'description': 'Find a Discord - the original discord server directory. Formerly /r/discordservers',
              'language': 'en',
              'favicon': null,
              'createdAt': '2021-09-26T17:18:09.739Z',
              'updatedAt': '2023-04-02T08:02:27.854Z',
              'isFeatured': false,
              'siteName': 'Find a Discord',
              'rank': '9007199254740991',
              'list_group_id': 305,
              'showcase_id': 108464,
              'position': 13000
            },
            {
              'id': 142848,
              'domain': 'stackoverflow.co',
              'hostname': 'stackoverflow.co',
              'url': 'https://stackoverflow.co:/',
              'hasSSR': true,
              'isStatic': true,
              'vueVersion': '3.2.47',
              'screenshotUrl': 'vue-telemetry/0a65a31bef06a53ee822fd5b9331c1bb.jpg',
              'slug': 'stackoverflow-co',
              'uiVersion': null,
              'frameworkVersion': null,
              'lastDetectedAt': '2023-04-05T14:04:56.034Z',
              'ui': {
                'id': 1,
                'slug': 'tailwind-css',
                'name': 'Tailwind CSS',
                'url': 'https://tailwindcss.com/',
                'imgPath': '/ui/tailwind.svg',
                'createdAt': '2020-06-24T09:13:44.270Z',
                'updatedAt': '2023-09-03T11:30:19.605Z'
              },
              'framework': {
                'id': 1,
                'slug': 'nuxtjs',
                'name': 'Nuxt',
                'url': 'https://nuxt.com',
                'imgPath': '/framework/nuxt.svg',
                'createdAt': '2020-06-23T12:39:28.355Z',
                'updatedAt': '2023-09-02T08:27:39.984Z'
              },
              'title': 'Empowering the world to develop technology through collective knowledge - Stack Overflow',
              'description': 'Founded in 2008, Stack Overflow’s public platform is used by nearly everyone who codes to learn, share their knowledge, collaborate, and build their careers.',
              'language': 'en',
              'favicon': null,
              'createdAt': '2022-02-11T05:54:27.595Z',
              'updatedAt': '2023-04-05T14:04:56.727Z',
              'isFeatured': false,
              'siteName': '',
              'rank': '9007199254740991',
              'list_group_id': 305,
              'showcase_id': 142848,
              'position': 17000
            },
            {
              'id': 242780,
              'domain': 'openai.com',
              'hostname': 'openai.com',
              'url': 'https://openai.com:/',
              'hasSSR': true,
              'isStatic': true,
              'vueVersion': '3.2.47',
              'screenshotUrl': 'vue-telemetry/467522ee638f6ff08a4489f280a08c29.jpg',
              'slug': 'openai-com',
              'uiVersion': null,
              'frameworkVersion': null,
              'lastDetectedAt': '2023-04-05T17:36:43.283Z',
              'ui': {
                'id': 1,
                'slug': 'tailwind-css',
                'name': 'Tailwind CSS',
                'url': 'https://tailwindcss.com/',
                'imgPath': '/ui/tailwind.svg',
                'createdAt': '2020-06-24T09:13:44.270Z',
                'updatedAt': '2023-09-03T11:30:19.605Z'
              },
              'framework': {
                'id': 1,
                'slug': 'nuxtjs',
                'name': 'Nuxt',
                'url': 'https://nuxt.com',
                'imgPath': '/framework/nuxt.svg',
                'createdAt': '2020-06-23T12:39:28.355Z',
                'updatedAt': '2023-09-02T08:27:39.984Z'
              },
              'title': 'OpenAI',
              'description': 'Introducing GPT-4, OpenAI’s most advanced system',
              'language': 'en',
              'favicon': null,
              'createdAt': '2023-02-28T22:40:46.712Z',
              'updatedAt': '2023-04-05T17:36:43.758Z',
              'isFeatured': false,
              'siteName': '',
              'rank': '9007199254740991',
              'list_group_id': 305,
              'showcase_id': 242780,
              'position': 500
            }
          ]
        },
        {
          'id': 306,
          'name': 'E-Commerce',
          'created_at': '2021-01-19T16:45:26.314Z',
          'updated_at': '2022-10-26T12:17:57.585Z',
          'position': 1000,
          'showcases': [
            {
              'id': 4760,
              'domain': 'system76.com',
              'hostname': 'system76.com',
              'url': 'https://system76.com:/',
              'hasSSR': true,
              'isStatic': false,
              'vueVersion': '2.7.14',
              'screenshotUrl': 'vue-telemetry/5c3c234467a020558420a701f5add2cd.jpg',
              'slug': 'system76-com',
              'uiVersion': null,
              'frameworkVersion': null,
              'lastDetectedAt': '2023-04-22T07:42:40.110Z',
              'ui': null,
              'framework': {
                'id': 1,
                'slug': 'nuxtjs',
                'name': 'Nuxt',
                'url': 'https://nuxt.com',
                'imgPath': '/framework/nuxt.svg',
                'createdAt': '2020-06-23T12:39:28.355Z',
                'updatedAt': '2023-09-02T08:27:39.984Z'
              },
              'title': 'System76 - Linux Laptops, Desktops, and Servers',
              'description': 'System76 computers empower the worlds  curious and capable makers of tomorrow',
              'language': 'en',
              'favicon': null,
              'createdAt': '2020-07-09T13:14:16.901Z',
              'updatedAt': '2023-04-22T07:42:41.562Z',
              'isFeatured': false,
              'siteName': '',
              'rank': '52666',
              'list_group_id': 306,
              'showcase_id': 4760,
              'position': 34000
            },
            {
              'id': 4793,
              'domain': 'backmarket.com',
              'hostname': 'backmarket.com',
              'url': 'https://backmarket.com:/',
              'hasSSR': true,
              'isStatic': false,
              'vueVersion': '2.7.14',
              'screenshotUrl': 'vue-telemetry/3903901eaa6b017a413840c2fef7af9b.jpg',
              'slug': 'backmarket-com',
              'uiVersion': null,
              'frameworkVersion': null,
              'lastDetectedAt': '2023-03-29T14:40:28.344Z',
              'ui': {
                'id': 1,
                'slug': 'tailwind-css',
                'name': 'Tailwind CSS',
                'url': 'https://tailwindcss.com/',
                'imgPath': '/ui/tailwind.svg',
                'createdAt': '2020-06-24T09:13:44.270Z',
                'updatedAt': '2023-09-03T11:30:19.605Z'
              },
              'framework': {
                'id': 1,
                'slug': 'nuxtjs',
                'name': 'Nuxt',
                'url': 'https://nuxt.com',
                'imgPath': '/framework/nuxt.svg',
                'createdAt': '2020-06-23T12:39:28.355Z',
                'updatedAt': '2023-09-02T08:27:39.984Z'
              },
              'title': 'Your Refurbished (Super) Market | Back Market',
              'description': 'Find the best deals on refurbished phones, laptops, and tech at Back Market. Up to 70% off when compared to new products. Free delivery, 1-year warranty, 30-day money back guarantee.',
              'language': 'en',
              'favicon': null,
              'createdAt': '2020-07-09T13:14:53.198Z',
              'updatedAt': '2023-03-29T14:40:28.730Z',
              'isFeatured': true,
              'siteName': '',
              'rank': '9007199254740991',
              'list_group_id': 306,
              'showcase_id': 4793,
              'position': 1000
            },
            {
              'id': 6818,
              'domain': 'stores.jp',
              'hostname': 'stores.jp',
              'url': 'https://stores.jp:/',
              'hasSSR': true,
              'isStatic': true,
              'vueVersion': '2.7.14',
              'screenshotUrl': 'vue-telemetry/ad683b95ffa5d8365fb80328943de38d.jpg',
              'slug': 'stores-jp',
              'uiVersion': null,
              'frameworkVersion': null,
              'lastDetectedAt': '2023-04-23T02:46:28.473Z',
              'ui': null,
              'framework': {
                'id': 1,
                'slug': 'nuxtjs',
                'name': 'Nuxt',
                'url': 'https://nuxt.com',
                'imgPath': '/framework/nuxt.svg',
                'createdAt': '2020-06-23T12:39:28.355Z',
                'updatedAt': '2023-09-02T08:27:39.984Z'
              },
              'title': 'STORES（ストアーズ）はあなたのお商売を応援します | まずはご相談ください | 無料ではじめられるネットショップなら、STORES ネットショップ',
              'description': 'STORES（ストアーズ）は初心者でもかんたんに始められるサービスを幅広く提供しています。ネットショップ開設から、お店のキャッシュレス化、POSレジ、予約システムの導入、店舗アプリ作成など、専門スタッフがあなたのお商売をサポートします。',
              'language': '',
              'favicon': null,
              'createdAt': '2020-07-09T13:53:27.854Z',
              'updatedAt': '2023-04-23T02:46:29.850Z',
              'isFeatured': false,
              'siteName': 'STORES',
              'rank': '9007199254740991',
              'list_group_id': 306,
              'showcase_id': 6818,
              'position': 2000
            },
            {
              'id': 9077,
              'domain': 'maisonsdumonde.com',
              'hostname': 'maisonsdumonde.com',
              'url': 'https://maisonsdumonde.com:/',
              'hasSSR': false,
              'isStatic': true,
              'vueVersion': '3.2.47',
              'screenshotUrl': 'vue-telemetry/72f0a5a6a02167b917b975d69e5d6187.jpg',
              'slug': 'maisonsdumonde-com',
              'uiVersion': null,
              'frameworkVersion': null,
              'lastDetectedAt': '2023-06-06T05:50:09.703Z',
              'ui': {
                'id': 1,
                'slug': 'tailwind-css',
                'name': 'Tailwind CSS',
                'url': 'https://tailwindcss.com/',
                'imgPath': '/ui/tailwind.svg',
                'createdAt': '2020-06-24T09:13:44.270Z',
                'updatedAt': '2023-09-03T11:30:19.605Z'
              },
              'framework': null,
              'title': 'Meuble, idée déco, canapé et luminaire | Maisons du Monde',
              'description': 'Tous les styles de meubles et déco sont chez Maisons du Monde ! Et avec des nouveautés toute l’année et la livraison gratuite en magasin, décorez à volonté.',
              'language': 'fr',
              'favicon': null,
              'createdAt': '2020-07-09T14:35:07.198Z',
              'updatedAt': '2023-06-06T05:50:09.888Z',
              'isFeatured': false,
              'siteName': '',
              'rank': '9007199254740991',
              'list_group_id': 306,
              'showcase_id': 9077,
              'position': 3000
            },
            {
              'id': 9175,
              'domain': 'happysocks.com',
              'hostname': 'happysocks.com',
              'url': 'https://happysocks.com:/',
              'hasSSR': true,
              'isStatic': false,
              'vueVersion': '2.6.14',
              'screenshotUrl': 'vue-telemetry/64b26453656aed8eca1796b21d412a55.jpg',
              'slug': 'happysocks-com',
              'uiVersion': null,
              'frameworkVersion': null,
              'lastDetectedAt': '2023-03-27T07:18:56.011Z',
              'ui': null,
              'framework': {
                'id': 1,
                'slug': 'nuxtjs',
                'name': 'Nuxt',
                'url': 'https://nuxt.com',
                'imgPath': '/framework/nuxt.svg',
                'createdAt': '2020-06-23T12:39:28.355Z',
                'updatedAt': '2023-09-02T08:27:39.984Z'
              },
              'title': 'Right now | Happy Socks EU',
              'description': 'Are you looking for designer socks, cosy socks, or cute socks? We ve got them all! We provide a wide collection of socks for all ages and all kinds of styles.',
              'language': 'en',
              'favicon': null,
              'createdAt': '2020-07-09T14:36:51.495Z',
              'updatedAt': '2023-03-27T07:18:56.935Z',
              'isFeatured': false,
              'siteName': 'Happy Socks',
              'rank': '9007199254740991',
              'list_group_id': 306,
              'showcase_id': 9175,
              'position': 4000
            },
            {
              'id': 9250,
              'domain': 'azazie.com',
              'hostname': 'azazie.com',
              'url': 'https://azazie.com:/',
              'hasSSR': true,
              'isStatic': false,
              'vueVersion': '2.6.11',
              'screenshotUrl': 'vue-telemetry/7c09e0138f09697b7d3ecb9e78c13565.jpg',
              'slug': 'azazie-com',
              'uiVersion': null,
              'frameworkVersion': null,
              'lastDetectedAt': '2023-04-03T11:49:29.249Z',
              'ui': null,
              'framework': {
                'id': 1,
                'slug': 'nuxtjs',
                'name': 'Nuxt',
                'url': 'https://nuxt.com',
                'imgPath': '/framework/nuxt.svg',
                'createdAt': '2020-06-23T12:39:28.355Z',
                'updatedAt': '2023-09-02T08:27:39.984Z'
              },
              'title': 'Robes demoiselle dhonneur, Robes de mariée et Robe de soirée | Azazie',
              'description': 'Azazie offre des robes de mariée et des robes de demoiselle dhonneur de haute qualité depuis 2014. Azazie est apparu sur The Today Show, CNBC et dautres médias populaires et a remporté le prix Glossy Beauty and Fashion Award pour la meilleure expérience de e-commerce. Avec des centaines de robes proposées dans une variété de silhouettes, de couleurs et de tailles, vous pouvez trouver la robe parfaite pour tout le monde.',
              'language': 'fr',
              'favicon': null,
              'createdAt': '2020-07-09T14:45:23.710Z',
              'updatedAt': '2023-04-03T11:49:30.096Z',
              'isFeatured': false,
              'siteName': 'Azazie',
              'rank': '9007199254740991',
              'list_group_id': 306,
              'showcase_id': 9250,
              'position': 5000
            },
            {
              'id': 42743,
              'domain': 'ohannesburger.com',
              'hostname': 'ohannesburger.com',
              'url': 'https://ohannesburger.com:/',
              'hasSSR': true,
              'isStatic': false,
              'vueVersion': '2.7.10',
              'screenshotUrl': 'vue-telemetry/2bc7ee39e8601c44b0cf039295c9d553.jpg',
              'slug': 'ohannesburger-com',
              'uiVersion': null,
              'frameworkVersion': null,
              'lastDetectedAt': '2023-04-26T04:40:05.664Z',
              'ui': {
                'id': 1,
                'slug': 'tailwind-css',
                'name': 'Tailwind CSS',
                'url': 'https://tailwindcss.com/',
                'imgPath': '/ui/tailwind.svg',
                'createdAt': '2020-06-24T09:13:44.270Z',
                'updatedAt': '2023-09-03T11:30:19.605Z'
              },
              'framework': {
                'id': 1,
                'slug': 'nuxtjs',
                'name': 'Nuxt',
                'url': 'https://nuxt.com',
                'imgPath': '/framework/nuxt.svg',
                'createdAt': '2020-06-23T12:39:28.355Z',
                'updatedAt': '2023-09-02T08:27:39.984Z'
              },
              'title': 'Ohannes Burger | Ohannes Farkı',
              'description': 'OhannesBurger’e hoşgeldiniz.\n\nBurada hamburgerler, patatesler ve köfteler her zaman sıcak, taze ve siparişten sonra yapılır. Yediğiniz en iyi burgeri yapmak için burdayız.\n\nOhannesBurger fikri iki taze endüstri mühendisinin Amerika macerasından, hamburgere duyulan tutkudan doğan bir obsesyon hikayesi.\n\nBiz;\nEğlenmeyi seven, ama sundukları ürünler konusunda çok ciddi olan insanlar. Tereyağlı brioche ekmeği, özel %100 yerli dana köftesi, taze malzemelerden üretilen günlük efsane soslar ve sıcacık patates kızartmalarından bahsediyoruz.\n\nYüksek kalite burgerleri sunarken, eğlenceyi elden bırakmayıp havalı, kendini beğenmiş bir mekan olmamaya özen gösteriyoruz. \n\nTaze olduğumuz kadar eğlenceli, zeki olduğumuz kadar yaratıcı, seçici olduğumuz kadar da oyuncuyuz.',
              'language': 'tr',
              'favicon': null,
              'createdAt': '2020-12-29T18:42:05.440Z',
              'updatedAt': '2023-04-26T04:40:06.089Z',
              'isFeatured': false,
              'siteName': '',
              'rank': '9007199254740991',
              'list_group_id': 571,
              'showcase_id': 42743,
              'position': 13000
            },
            {
              'id': 46466,
              'domain': 'deliveroo.fr',
              'hostname': 'riders.deliveroo.fr',
              'url': 'https://riders.deliveroo.fr/fr/news/verifiez-votre-identite-et-securisez-votre-compte-en-une-photo',
              'hasSSR': true,
              'isStatic': false,
              'vueVersion': '2.6.12',
              'screenshotUrl': 'vue-telemetry/f49409275985b230678c3cd5e781ce19.jpg',
              'slug': 'riders-deliveroo-fr',
              'uiVersion': null,
              'frameworkVersion': null,
              'lastDetectedAt': '2022-12-11T00:46:21.984Z',
              'ui': null,
              'framework': {
                'id': 1,
                'slug': 'nuxtjs',
                'name': 'Nuxt',
                'url': 'https://nuxt.com',
                'imgPath': '/framework/nuxt.svg',
                'createdAt': '2020-06-23T12:39:28.355Z',
                'updatedAt': '2023-09-02T08:27:39.984Z'
              },
              'title': 'Deliveroo | Vérifiez votre identité et sécurisez votre compte en une photo',
              'description': '',
              'language': '',
              'favicon': null,
              'createdAt': '2021-01-14T10:37:58.773Z',
              'updatedAt': '2022-12-11T00:46:22.150Z',
              'isFeatured': false,
              'siteName': '',
              'rank': '32396',
              'list_group_id': 571,
              'showcase_id': 46466,
              'position': 875
            },
            {
              'id': 48791,
              'domain': 'asencis.com',
              'hostname': 'asencis.com',
              'url': 'https://asencis.com:/',
              'hasSSR': true,
              'isStatic': true,
              'vueVersion': '2.6.12',
              'screenshotUrl': 'vue-telemetry/e8ea886c67091b2a4debeab975d0c476.jpg',
              'slug': 'asencis-com',
              'uiVersion': null,
              'frameworkVersion': null,
              'lastDetectedAt': '2023-04-11T09:05:46.147Z',
              'ui': {
                'id': 1,
                'slug': 'tailwind-css',
                'name': 'Tailwind CSS',
                'url': 'https://tailwindcss.com/',
                'imgPath': '/ui/tailwind.svg',
                'createdAt': '2020-06-24T09:13:44.270Z',
                'updatedAt': '2023-09-03T11:30:19.605Z'
              },
              'framework': {
                'id': 1,
                'slug': 'nuxtjs',
                'name': 'Nuxt',
                'url': 'https://nuxt.com',
                'imgPath': '/framework/nuxt.svg',
                'createdAt': '2020-06-23T12:39:28.355Z',
                'updatedAt': '2023-09-02T08:27:39.984Z'
              },
              'title': 'Open Data Publishing Specialists | asencis',
              'description': 'The world is opening up, so should your data; create global openness to data whilst making your research more transparent, collaborative and efficient.',
              'language': 'en',
              'favicon': null,
              'createdAt': '2021-01-21T13:58:12.985Z',
              'updatedAt': '2023-04-11T09:05:46.453Z',
              'isFeatured': false,
              'siteName': '',
              'rank': '9007199254740991',
              'list_group_id': 571,
              'showcase_id': 48791,
              'position': 16000
            },
            {
              'id': 66297,
              'domain': 'unilever.com',
              'hostname': 'unilever.com',
              'url': 'https://unilever.com:/',
              'hasSSR': false,
              'isStatic': true,
              'vueVersion': '3.3.4',
              'screenshotUrl': 'vue-telemetry/f88bac390770d6bcf39f6c041cf00897.jpg',
              'slug': 'unilever-com',
              'uiVersion': null,
              'frameworkVersion': null,
              'lastDetectedAt': '2023-08-09T13:42:16.973Z',
              'ui': {
                'id': 1,
                'slug': 'tailwind-css',
                'name': 'Tailwind CSS',
                'url': 'https://tailwindcss.com/',
                'imgPath': '/ui/tailwind.svg',
                'createdAt': '2020-06-24T09:13:44.270Z',
                'updatedAt': '2023-09-03T11:30:19.605Z'
              },
              'framework': null,
              'title': 'Unilever Global: Making sustainable living commonplace | Unilever',
              'description': 'At Unilever we meet everyday needs for nutrition, hygiene and personal care with brands that help people feel good, look good and get more out of life.',
              'language': 'en',
              'favicon': null,
              'createdAt': '2021-03-22T08:58:50.312Z',
              'updatedAt': '2023-08-09T13:42:17.265Z',
              'isFeatured': false,
              'siteName': 'Unilever',
              'rank': '9007199254740991',
              'list_group_id': 571,
              'showcase_id': 66297,
              'position': 19000
            },
            {
              'id': 86352,
              'domain': 'deliveroo.co.uk',
              'hostname': 'riders.deliveroo.co.uk',
              'url': 'https://riders.deliveroo.co.uk:/',
              'hasSSR': true,
              'isStatic': false,
              'vueVersion': '2.6.12',
              'screenshotUrl': 'vue-telemetry/549023dc59232b24b54e5a5e62410fea.jpg',
              'slug': 'riders-deliveroo-co-uk',
              'uiVersion': null,
              'frameworkVersion': null,
              'lastDetectedAt': '2023-04-21T04:02:35.465Z',
              'ui': null,
              'framework': {
                'id': 1,
                'slug': 'nuxtjs',
                'name': 'Nuxt',
                'url': 'https://nuxt.com',
                'imgPath': '/framework/nuxt.svg',
                'createdAt': '2020-06-23T12:39:28.355Z',
                'updatedAt': '2023-09-02T08:27:39.984Z'
              },
              'title': 'Deliveroo | Deliveroo Riders UK',
              'description': '',
              'language': '',
              'favicon': null,
              'createdAt': '2021-06-11T14:30:48.163Z',
              'updatedAt': '2023-04-21T04:02:35.743Z',
              'isFeatured': false,
              'siteName': '',
              'rank': '9007199254740991',
              'list_group_id': 571,
              'showcase_id': 86352,
              'position': 18000
            },
            {
              'id': 112208,
              'domain': 'logic-immo.be',
              'hostname': 'logic-immo.be',
              'url': 'https://logic-immo.be/',
              'hasSSR': true,
              'isStatic': false,
              'vueVersion': '2.6.12',
              'screenshotUrl': 'vue-telemetry/43c6d85b8a20b91d9a591c20790b3e59.jpg',
              'slug': 'logic-immo-be',
              'uiVersion': null,
              'frameworkVersion': null,
              'lastDetectedAt': '2022-11-09T01:07:50.338Z',
              'ui': {
                'id': 1,
                'slug': 'tailwind-css',
                'name': 'Tailwind CSS',
                'url': 'https://tailwindcss.com/',
                'imgPath': '/ui/tailwind.svg',
                'createdAt': '2020-06-24T09:13:44.270Z',
                'updatedAt': '2023-09-03T11:30:19.605Z'
              },
              'framework': {
                'id': 1,
                'slug': 'nuxtjs',
                'name': 'Nuxt',
                'url': 'https://nuxt.com',
                'imgPath': '/framework/nuxt.svg',
                'createdAt': '2020-06-23T12:39:28.355Z',
                'updatedAt': '2023-09-02T08:27:39.984Z'
              },
              'title': 'Logic-Immo.be',
              'description': 'Logic-Immo.be is a real estate classifieds website dedicated to Belgium. It presents listings of properties from real estate professionnals !',
              'language': 'en',
              'favicon': null,
              'createdAt': '2021-10-11T20:00:29.322Z',
              'updatedAt': '2022-11-09T01:07:50.549Z',
              'isFeatured': false,
              'siteName': '',
              'rank': '188228',
              'list_group_id': 571,
              'showcase_id': 112208,
              'position': 20000
            },
            {
              'id': 114763,
              'domain': 'okok.services',
              'hostname': 'areyou.okok.services',
              'url': 'https://areyou.okok.services:/shop',
              'hasSSR': true,
              'isStatic': true,
              'vueVersion': '2.6.14',
              'screenshotUrl': 'vue-telemetry/e89c784432c0114cb1b74e95b1cde66a.jpg',
              'slug': 'areyou-okok-services',
              'uiVersion': null,
              'frameworkVersion': null,
              'lastDetectedAt': '2023-04-20T04:44:32.647Z',
              'ui': null,
              'framework': {
                'id': 1,
                'slug': 'nuxtjs',
                'name': 'Nuxt',
                'url': 'https://nuxt.com',
                'imgPath': '/framework/nuxt.svg',
                'createdAt': '2020-06-23T12:39:28.355Z',
                'updatedAt': '2023-09-02T08:27:39.984Z'
              },
              'title': 'ARE YOU OKOK? - Shop',
              'description': 'Measuring equipments for true emotional readings, by OKOK Services.',
              'language': 'en',
              'favicon': null,
              'createdAt': '2021-10-20T17:08:57.980Z',
              'updatedAt': '2023-04-20T04:44:32.967Z',
              'isFeatured': false,
              'siteName': 'okok-meter',
              'rank': '9007199254740991',
              'list_group_id': 672,
              'showcase_id': 114763,
              'position': 33000
            },
            {
              'id': 116063,
              'domain': 'magnetism.fr',
              'hostname': 'magnetism.fr',
              'url': 'https://magnetism.fr/',
              'hasSSR': true,
              'isStatic': true,
              'vueVersion': '2.6.14',
              'screenshotUrl': 'vue-telemetry/a17cd500b6ba4a2e8a0579245bf2bc82.jpg',
              'slug': 'magnetism-fr',
              'uiVersion': null,
              'frameworkVersion': null,
              'lastDetectedAt': '2022-12-10T01:45:48.608Z',
              'ui': null,
              'framework': {
                'id': 1,
                'slug': 'nuxtjs',
                'name': 'Nuxt',
                'url': 'https://nuxt.com',
                'imgPath': '/framework/nuxt.svg',
                'createdAt': '2020-06-23T12:39:28.355Z',
                'updatedAt': '2023-09-02T08:27:39.984Z'
              },
              'title': 'Magnetism | Agence de Création',
              'description': 'Magnetism - Agence de Création, basée à Paris, accompagne les marques pour les rendre attractives : stratégie, design, publicité et digital.',
              'language': 'fr',
              'favicon': null,
              'createdAt': '2021-10-25T16:45:20.400Z',
              'updatedAt': '2022-12-10T01:45:48.768Z',
              'isFeatured': false,
              'siteName': '',
              'rank': '1414127',
              'list_group_id': 672,
              'showcase_id': 116063,
              'position': 27000
            },
            {
              'id': 116073,
              'domain': 'saleshunter.com',
              'hostname': 'saleshunter.com',
              'url': 'https://saleshunter.com:/',
              'hasSSR': true,
              'isStatic': true,
              'vueVersion': '2.6.14',
              'screenshotUrl': 'vue-telemetry/af0eb9dd6f97fa2163dd24f741c3beb6.jpg',
              'slug': 'saleshunter-com',
              'uiVersion': null,
              'frameworkVersion': null,
              'lastDetectedAt': '2023-04-25T04:23:28.204Z',
              'ui': null,
              'framework': {
                'id': 1,
                'slug': 'nuxtjs',
                'name': 'Nuxt',
                'url': 'https://nuxt.com',
                'imgPath': '/framework/nuxt.svg',
                'createdAt': '2020-06-23T12:39:28.355Z',
                'updatedAt': '2023-09-02T08:27:39.984Z'
              },
              'title': 'SalesHunter — Get all your sales reps to perform like the top 1%',
              'description': 'Get all your sales teams perform like top 1% with SalesHunter AI-powered sales optimization and recommendation tool. Built for wholesaler, manufacturer and distributor teams.',
              'language': 'en',
              'favicon': null,
              'createdAt': '2021-10-25T17:27:26.454Z',
              'updatedAt': '2023-04-25T04:23:28.451Z',
              'isFeatured': false,
              'siteName': 'SalesHunter',
              'rank': '9007199254740991',
              'list_group_id': 672,
              'showcase_id': 116073,
              'position': 31000
            },
            {
              'id': 118723,
              'domain': 'clementbalavoine.com',
              'hostname': 'clementbalavoine.com',
              'url': 'https://clementbalavoine.com:/projects',
              'hasSSR': true,
              'isStatic': true,
              'vueVersion': '2.6.14',
              'screenshotUrl': 'vue-telemetry/3345b3441bab0b3dc05431f5bca78054.jpg',
              'slug': 'clementbalavoine-com',
              'uiVersion': null,
              'frameworkVersion': null,
              'lastDetectedAt': '2023-04-22T04:30:49.128Z',
              'ui': null,
              'framework': {
                'id': 1,
                'slug': 'nuxtjs',
                'name': 'Nuxt',
                'url': 'https://nuxt.com',
                'imgPath': '/framework/nuxt.svg',
                'createdAt': '2020-06-23T12:39:28.355Z',
                'updatedAt': '2023-09-02T08:27:39.984Z'
              },
              'title': 'Clément Balavoine© | Product Visualization Lead at Meta',
              'description': 'Clement Balavoine is a Director+Designer living in Seattle and is currently leading the product visualization group at Meta Reality Labs. Clementbody of work includes collaborations with Nike, Adidas Originals, Hamcus, The North Face, Oculus, Louis Vuitton and more.',
              'language': '',
              'favicon': null,
              'createdAt': '2021-11-04T10:45:43.218Z',
              'updatedAt': '2023-04-22T04:30:49.379Z',
              'isFeatured': false,
              'siteName': '',
              'rank': '9007199254740991',
              'list_group_id': 672,
              'showcase_id': 118723,
              'position': 30000
            },
            {
              'id': 119909,
              'domain': 'rvlt.net',
              'hostname': 'rvlt.net',
              'url': 'https://rvlt.net:/',
              'hasSSR': true,
              'isStatic': true,
              'vueVersion': '2.7.14',
              'screenshotUrl': 'vue-telemetry/2fe6ffe0c865c4c0e5c1455dedfc1baf.jpg',
              'slug': 'rvlt-net',
              'uiVersion': null,
              'frameworkVersion': null,
              'lastDetectedAt': '2023-04-07T05:42:08.424Z',
              'ui': null,
              'framework': {
                'id': 1,
                'slug': 'nuxtjs',
                'name': 'Nuxt',
                'url': 'https://nuxt.com',
                'imgPath': '/framework/nuxt.svg',
                'createdAt': '2020-06-23T12:39:28.355Z',
                'updatedAt': '2023-09-02T08:27:39.984Z'
              },
              'title': 'Revolt - Changing the Landscape of Merchandising',
              'description': 'Revolt a one-stop-shop for seamless influencer merchandising.',
              'language': 'en',
              'favicon': null,
              'createdAt': '2021-11-09T09:44:04.983Z',
              'updatedAt': '2023-04-07T05:42:08.766Z',
              'isFeatured': false,
              'siteName': 'Revolt',
              'rank': '9007199254740991',
              'list_group_id': 672,
              'showcase_id': 119909,
              'position': 28000
            },
            {
              'id': 137999,
              'domain': 'keepgrading.com',
              'hostname': 'keepgrading.com',
              'url': 'https://keepgrading.com:/',
              'hasSSR': true,
              'isStatic': true,
              'vueVersion': '2.6.14',
              'screenshotUrl': 'vue-telemetry/fa6ea31ef013b0181a1dcebde2c3ecee.jpg',
              'slug': 'keepgrading-com',
              'uiVersion': null,
              'frameworkVersion': null,
              'lastDetectedAt': '2023-04-12T10:22:24.817Z',
              'ui': {
                'id': 1,
                'slug': 'tailwind-css',
                'name': 'Tailwind CSS',
                'url': 'https://tailwindcss.com/',
                'imgPath': '/ui/tailwind.svg',
                'createdAt': '2020-06-24T09:13:44.270Z',
                'updatedAt': '2023-09-03T11:30:19.605Z'
              },
              'framework': {
                'id': 1,
                'slug': 'nuxtjs',
                'name': 'Nuxt',
                'url': 'https://nuxt.com',
                'imgPath': '/framework/nuxt.svg',
                'createdAt': '2020-06-23T12:39:28.355Z',
                'updatedAt': '2023-09-02T08:27:39.984Z'
              },
              'title': 'KeepGrading - A colour grading post production studio',
              'description': 'We are KeepGrading, a post production studio focused on colour grading based in Paris, France. We work mainly on advertisements, music videos and film.',
              'language': 'en',
              'favicon': null,
              'createdAt': '2022-01-23T10:28:49.863Z',
              'updatedAt': '2023-04-12T10:22:25.310Z',
              'isFeatured': false,
              'siteName': 'KeepGrading',
              'rank': '9007199254740991',
              'list_group_id': 672,
              'showcase_id': 137999,
              'position': 37000
            }
          ]
        }
      ]
    }
     ]
})
